### ISSUE TITLE
Change row.xml

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#13]
Change row.xml by adding :
`Character Name (Text)`
`Character Image (Circular Image)`
`Character House (Text)`
`Favourite Button (Red Heart Image)`

Design the `row.xml` in a GoT themed way (preferably dark theme).

For any doubts join the discord channel provided in the GeekHaven mail.
This issue is now open for all so the best design would be merged :)

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by Devildarkfire** [comment]
I want to work on this

**Comment by JLodha** [comment]
I would like to work

**Comment by VarunT11** [comment]
@Mandar16 Sorry, but you cannot work on more than one issue in a single repo. Once you complete the issue, you can work on other issues.

**Comment by VarunT11** [comment]
@Devildarkfire Go Ahead

**Comment by Pranshu-Tripathi** [comment]
Can i work on this ?

**Comment by starboi02** [comment]
@JLodha @Mandar16 respond if you guys too are working on it.
