### ISSUE TITLE
Make character.java file 

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#16]
Make a character.java file containing character class with constructor having arguments : `character name`, `character image url`, `character house` , `name of people killed (ArrayList)` , `killed by (ArrayList )` , `parents` , `siblings` and `spouse` .
Also make different methods to retrive these values e.g. `getCharacterName()` which would return the character name.

**Comment by Devildarkfire** [comment]
I would like to work on this

**Comment by Mandar16** [comment]
I would like to work on this issue

**Comment by starboi02** [comment]
@Devildarkfire you will be assigned it after your previous PR is merged.

**Comment by starboi02** [comment]
@Mandar16 go ahead !

**Comment by deepakgupta124** [comment]
Can I work on this issue?
