### ISSUE TITLE
Add heart icon to toolbar in Main Activity

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#21]

**Comment by natzoz** [comment]
Hello, can I try this? @starboi02

**Comment by EikeSan** [comment]
Hello @starboi02 , can you give a more detailed description? 
Is just add an icon or add the functionality do fill the heart on rolls when it's pressed?

**Comment by starboi02** [comment]
@natzoz @EikeSan sorry this is a college event so we are not entertaining PRs outside the college domain :(

**Comment by Devildarkfire** [comment]
I want to work on this

**Comment by starboi02** [comment]
@Devildarkfire go ahead.
