### ISSUE TITLE
Change background color and Toolbar color 

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#22]
Change color scheme to something suitable preferably dark.

**Comment by CadencePrestissimo** [comment]
Can I do this ?

**Comment by EikeSan** [comment]
Hello @starboi02, I made this on #23 .

![Captura de tela de 2020-10-15 23-41-05](https://user-images.githubusercontent.com/13926450/96206755-fd2eef80-0f3f-11eb-9a46-1cf72b8543ec.png)

**Comment by starboi02** [comment]
@EikeSan nice work dude but unfortunately we cant entertain your PR as this is a college event :(.

**Comment by starboi02** [comment]
@CadencePrestissimo go ahead.

**Comment by Codedude1** [comment]
I would like to contribute.
