### ISSUE TITLE
Add children parameter to Character class

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#25]
Add children attribute (ArrayList) and its methods to Character class.

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by Pranshu-Tripathi** [comment]
Can I add this ?

**Comment by starboi02** [comment]
@Mandar16 @Pranshu-Tripathi you both are well versed with android dev so lets leave it to someone who is new to it :)

**Comment by rishier827** [comment]
can i get assigned

**Comment by starboi02** [comment]
@rishier827 sorry but this event is specific to our college so no outside PRs would be merged :(

**Comment by DevilAJ** [comment]
Can I work on it.

**Comment by starboi02** [comment]
@DevilAJ sure go ahead

**Comment by Codedude1** [comment]
Is this open? I want to contribute.
