### ISSUE TITLE
Add logo to app

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#3]
Add a suitable GOT themed icon as application logo.

**Comment by JLodha** [comment]
I want to work on this

**Comment by starboi02** [comment]
@JLodha Sure go ahead !

**Comment by Mandar16** [comment]
I would like to work on this.

**Comment by Devildarkfire** [comment]
I want to work on this

**Comment by starboi02** [comment]
@JLodha please add your contribution to https://github.com/GeekHaven/Geektoberfest-Main

**Comment by JLodha** [comment]
> @JLodha please add your contribution to https://github.com/GeekHaven/Geektoberfest-Main

I did
