### ISSUE TITLE
Add methods to CharacterItem class

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#34]
Add ``` setFavourite() ``` and ```getFavourite()``` methods inside CharacterItem.class. Use boolean as data type for favourite .

**Comment by DevilAJ** [comment]
I want to work on it.

**Comment by VarunT11** [comment]
@DevilAJ Sure! Go Ahead

**Comment by DevilAJ** [comment]
@VarunT11  

Like this..?

![image](https://user-images.githubusercontent.com/58396277/96403054-05638500-11f5-11eb-8b85-aa6ba6f9be79.png)

![image](https://user-images.githubusercontent.com/58396277/96409555-13b89d80-1203-11eb-8472-8940b0621da8.png)

**Comment by starboi02** [comment]
@DevilAJ remove favourite from the constructor and make favourite default value as false moreover the setFavourite method would have a boolean as an attribute which would change the value of favourite variable.

**Comment by DevilAJ** [comment]
Is this ok

![image](https://user-images.githubusercontent.com/58396277/96409906-ae18e100-1203-11eb-94aa-4f0d65bd3d02.png)

![image](https://user-images.githubusercontent.com/58396277/96409922-b7a24900-1203-11eb-8272-3a2a074d7b71.png)

**Comment by starboi02** [comment]
@DevilAJ remove '' this.favourite=false '' from the constructor instead make '' private boolean favourite = false '' as the initializer.
