### ISSUE TITLE
Add FAB to main activity

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#39]
The recycler view list is very big so upon scrolling a FAB should appear on bottom right and by clicking on which it will guide us to the top of the recycler view.

**Comment by siddhantdrk** [comment]
I would like to work on it

**Comment by Pranshu-Tripathi** [comment]
Can I Work ?

**Comment by starboi02** [comment]
@Pranshu-Tripathi sure go ahead!
btw how many PRs have you made in GeekTober yet?

**Comment by Pranshu-Tripathi** [comment]
4 merged PRs and one was not merged(Row.xml one)
