### ISSUE TITLE
Implement onClickListner for items of recycler view

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#43]
Pass ```CharacterItem``` to the screen where data would be shown.

**Comment by DevilAJ** [comment]
Can I work on it

**Comment by starboi02** [comment]
@DevilAJ how many PRs have you made ?

**Comment by Mandar16** [comment]
I would like to work on this.

**Comment by DevilAJ** [comment]
5 pr

**Comment by starboi02** [comment]
@Mandar16 you can grab other unassigned issues as well and feel free to ask if you get stuck anywhere.

**Comment by DevilAJ** [comment]
@starboi02 

Can you please explain exactly what I have to do.
