### ISSUE TITLE
Add CharacterItem List to database

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#49]
For the first time CharacterItems should be added to database (method already defined in ```DatabaseHandler``` ). Subsequently CharacterItem should be shown through database not through server fetching.

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by starboi02** [comment]
@Mandar16 go ahead!

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by deepak-gup7a** [comment]
Can I work on this issue?

**Comment by starboi02** [comment]
@deepakgupta124 go ahead
