### ISSUE TITLE
Filter list by clicking on icon on toolbar

### ISSUE THREAD

**Issue by starboi02** [GeekHaven/GOT-Character-App#50]
On clicking heart icon on the toolbar the list should be filtered and show only favourite characters.

**Comment by Mandar16** [comment]
I would like to work on this

**Comment by starboi02** [comment]
@Mandar16 go ahead

**Comment by starboi02** [comment]
@Mandar16 what's the status?

**Comment by Mandar16** [comment]
@starboi02 Made the PR already.
